

let sampleProjects: [Project] = [
    Project(name: "WeatherWizard", features: [
        "Hourly Forecast",
        "10-Day Outlook",
        "Radar Map",
        "Severe Storm Alerts",
        "Air Quality Index",
        "UV Index",
        "Sunrise & Sunset",
        "Widget Support",
        "Location-Based Notifications",
        "WatchOS Companion",
        "iPad Split View",
        "Dark Mode",
        "Siri Shortcuts",
        "Home Screen Quick Actions",
        "Offline Caching",
        "Customizable Themes",
        "Wind Speed Graph",
        "Humidity Chart",
        "Pressure Trends",
        "Precipitation Chances",
        "Haptic Feedback Alerts",
        "Live Activity",
        "Interactive Radar Layers",
        "Shareable Weather Cards",
        "CarPlay Forecast Screen",
        "Hourly Forecast",
        "10-Day Outlook",
        "Radar Map",
        "Severe Storm Alerts",
        "Air Quality Index",
        "UV Index",
        "Sunrise & Sunset",
        "Widget Support",
        "Location-Based Notifications",
        "WatchOS Companion",
        "iPad Split View",
        "Dark Mode",
        "Siri Shortcuts",
        "Home Screen Quick Actions",
        "Offline Caching",
        "Customizable Themes",
        "Wind Speed Graph",
        "Humidity Chart",
        "Pressure Trends",
        "Precipitation Chances",
        "Haptic Feedback Alerts",
        "Live Activity",
        "Interactive Radar Layers",
        "Shareable Weather Cards",
        "CarPlay Forecast Screen"
    ]),
    Project(name: "BudgetBuddy", features: [
        "Expense Tracking",
        "Recurring Bills Reminders",
        "Multi-Currency Support",
        "Budget Goals",
        "Spending Categories",
        "Savings Tracker",
        "Export to CSV",
        "Bill Payment Notifications",
        "Dark Mode",
        "Widgets for Quick View",
        "Hourly Forecast",
        "10-Day Outlook",
        "Radar Map",
        "Severe Storm Alerts",
        "Air Quality Index",
        "UV Index",
        "Sunrise & Sunset",
        "Widget Support",
        "Location-Based Notifications",
        "WatchOS Companion",
        "iPad Split View",
        "Dark Mode",
        "Siri Shortcuts",
        "Home Screen Quick Actions",
        "Offline Caching",
        "Customizable Themes",
        "Wind Speed Graph",
        "Humidity Chart",
        "Pressure Trends",
        "Precipitation Chances",
        "Haptic Feedback Alerts",
        "Live Activity",
        "Interactive Radar Layers",
        "Shareable Weather Cards",
        "CarPlay Forecast Screen"
    ]),
    Project(name: "FitTrack", features: [
        "Workout Plans",
        "Calorie Counter",
        "Step Tracker",
        "Heart Rate Monitor",
        "Sleep Analysis",
        "Water Intake Reminders",
        "GPS Run Tracking",
        "Apple Watch Support",
        "Goal Setting",
        "Progress Charts",
        "Hourly Forecast",
        "10-Day Outlook",
        "Radar Map",
        "Severe Storm Alerts",
        "Air Quality Index",
        "UV Index",
        "Sunrise & Sunset",
        "Widget Support",
        "Location-Based Notifications",
        "WatchOS Companion",
        "iPad Split View",
        "Dark Mode",
        "Siri Shortcuts",
        "Home Screen Quick Actions",
        "Offline Caching",
        "Customizable Themes",
        "Wind Speed Graph",
        "Humidity Chart",
        "Pressure Trends",
        "Precipitation Chances",
        "Haptic Feedback Alerts",
        "Live Activity",
        "Interactive Radar Layers",
        "Shareable Weather Cards",
        "CarPlay Forecast Screen"
    ]),
    Project(name: "RecipeMaster", features: [
        "Recipe Search",
        "Meal Planner",
        "Shopping List",
        "Nutritional Info",
        "Favorites",
        "Voice Search",
        "Offline Recipes",
        "Cooking Mode",
        "Share Recipes",
        "Ingredient Substitutions",
        "Hourly Forecast",
        "10-Day Outlook",
        "Radar Map",
        "Severe Storm Alerts",
        "Air Quality Index",
        "UV Index",
        "Sunrise & Sunset",
        "Widget Support",
        "Location-Based Notifications",
        "WatchOS Companion",
        "iPad Split View",
        "Dark Mode",
        "Siri Shortcuts",
        "Home Screen Quick Actions",
        "Offline Caching",
        "Customizable Themes",
        "Wind Speed Graph",
        "Humidity Chart",
        "Pressure Trends",
        "Precipitation Chances",
        "Haptic Feedback Alerts",
        "Live Activity",
        "Interactive Radar Layers",
        "Shareable Weather Cards",
        "CarPlay Forecast Screen"
    ]),
    Project(name: "TravelMate", features: [
        "Flight Tracker",
        "Hotel Booking",
        "Currency Converter",
        "Weather Forecast",
        "Trip Planner",
        "Offline Maps",
        "Travel Itinerary",
        "Local Attractions",
        "Language Translator",
        "Expense Tracker",
        "Hourly Forecast",
        "10-Day Outlook",
        "Radar Map",
        "Severe Storm Alerts",
        "Air Quality Index",
        "UV Index",
        "Sunrise & Sunset",
        "Widget Support",
        "Location-Based Notifications",
        "WatchOS Companion",
        "iPad Split View",
        "Dark Mode",
        "Siri Shortcuts",
        "Home Screen Quick Actions",
        "Offline Caching",
        "Customizable Themes",
        "Wind Speed Graph",
        "Humidity Chart",
        "Pressure Trends",
        "Precipitation Chances",
        "Haptic Feedback Alerts",
        "Live Activity",
        "Interactive Radar Layers",
        "Shareable Weather Cards",
        "CarPlay Forecast Screen"
    ]),
    Project(name: "Learnify", features: [
        "Course Library",
        "Video Lessons",
        "Quizzes",
        "Offline Access",
        "Progress Tracker",
        "Certificates",
        "Dark Mode",
        "Bookmarks",
        "Push Notifications",
        "Multi-Language Support",
        "Hourly Forecast",
        "10-Day Outlook",
        "Radar Map",
        "Severe Storm Alerts",
        "Air Quality Index",
        "UV Index",
        "Sunrise & Sunset",
        "Widget Support",
        "Location-Based Notifications",
        "WatchOS Companion",
        "iPad Split View",
        "Dark Mode",
        "Siri Shortcuts",
        "Home Screen Quick Actions",
        "Offline Caching",
        "Customizable Themes",
        "Wind Speed Graph",
        "Humidity Chart",
        "Pressure Trends",
        "Precipitation Chances",
        "Haptic Feedback Alerts",
        "Live Activity",
        "Interactive Radar Layers",
        "Shareable Weather Cards",
        "CarPlay Forecast Screen"
    ]),
    Project(name: "ShopSmart", features: [
        "Price Comparison",
        "Barcode Scanner",
        "Wishlist",
        "Discount Alerts",
        "Order Tracking",
        "Reviews & Ratings",
        "Store Locator",
        "Secure Checkout",
        "Favorites",
        "Flash Sale Notifications",
        "Hourly Forecast",
        "10-Day Outlook",
        "Radar Map",
        "Severe Storm Alerts",
        "Air Quality Index",
        "UV Index",
        "Sunrise & Sunset",
        "Widget Support",
        "Location-Based Notifications",
        "WatchOS Companion",
        "iPad Split View",
        "Dark Mode",
        "Siri Shortcuts",
        "Home Screen Quick Actions",
        "Offline Caching",
        "Customizable Themes",
        "Wind Speed Graph",
        "Humidity Chart",
        "Pressure Trends",
        "Precipitation Chances",
        "Haptic Feedback Alerts",
        "Live Activity",
        "Interactive Radar Layers",
        "Shareable Weather Cards",
        "CarPlay Forecast Screen"
    ]),
    Project(name: "PetCare", features: [
        "Pet Profiles",
        "Vet Appointments",
        "Vaccination Reminders",
        "Pet Food Tracker",
        "Activity Log",
        "Weight Monitoring",
        "Photo Gallery",
        "Lost Pet Alerts",
        "Nearby Pet Services",
        "Medication Schedule",
        "Hourly Forecast",
        "10-Day Outlook",
        "Radar Map",
        "Severe Storm Alerts",
        "Air Quality Index",
        "UV Index",
        "Sunrise & Sunset",
        "Widget Support",
        "Location-Based Notifications",
        "WatchOS Companion",
        "iPad Split View",
        "Dark Mode",
        "Siri Shortcuts",
        "Home Screen Quick Actions",
        "Offline Caching",
        "Customizable Themes",
        "Wind Speed Graph",
        "Humidity Chart",
        "Pressure Trends",
        "Precipitation Chances",
        "Haptic Feedback Alerts",
        "Live Activity",
        "Interactive Radar Layers",
        "Shareable Weather Cards",
        "CarPlay Forecast Screen"
    ]),
    Project(name: "MovieMania", features: [
        "Now Playing",
        "Upcoming Movies",
        "Top Rated",
        "Search",
        "Watchlist",
        "Trailers",
        "Reviews",
        "Cast & Crew Info",
        "Showtimes",
        "Streaming Availability",
        "Hourly Forecast",
        "10-Day Outlook",
        "Radar Map",
        "Severe Storm Alerts",
        "Air Quality Index",
        "UV Index",
        "Sunrise & Sunset",
        "Widget Support",
        "Location-Based Notifications",
        "WatchOS Companion",
        "iPad Split View",
        "Dark Mode",
        "Siri Shortcuts",
        "Home Screen Quick Actions",
        "Offline Caching",
        "Customizable Themes",
        "Wind Speed Graph",
        "Humidity Chart",
        "Pressure Trends",
        "Precipitation Chances",
        "Haptic Feedback Alerts",
        "Live Activity",
        "Interactive Radar Layers",
        "Shareable Weather Cards",
        "CarPlay Forecast Screen",
        "Hourly Forecast",
        "10-Day Outlook",
        "Radar Map",
        "Severe Storm Alerts",
        "Air Quality Index",
        "UV Index",
        "Sunrise & Sunset",
        "Widget Support",
        "Location-Based Notifications",
        "WatchOS Companion",
        "iPad Split View",
        "Dark Mode",
        "Siri Shortcuts",
        "Home Screen Quick Actions",
        "Offline Caching",
        "Customizable Themes",
        "Wind Speed Graph",
        "Humidity Chart",
        "Pressure Trends",
        "Precipitation Chances",
        "Haptic Feedback Alerts",
        "Live Activity",
        "Interactive Radar Layers",
        "Shareable Weather Cards",
        "CarPlay Forecast Screen"
    ]),
    Project(name: "HomeControl", features: [
        "Smart Light Control",
        "Thermostat Adjustment",
        "Security Camera Feed",
        "Door Lock Control",
        "Energy Usage Monitor",
        "Scene Automation",
        "Voice Assistant Integration",
        "Appliance Scheduling",
        "Custom Scenes",
        "Alerts & Notifications",
        "Hourly Forecast",
        "10-Day Outlook",
        "Radar Map",
        "Severe Storm Alerts",
        "Air Quality Index",
        "UV Index",
        "Sunrise & Sunset",
        "Widget Support",
        "Location-Based Notifications",
        "WatchOS Companion",
        "iPad Split View",
        "Dark Mode",
        "Siri Shortcuts",
        "Home Screen Quick Actions",
        "Offline Caching",
        "Customizable Themes",
        "Wind Speed Graph",
        "Humidity Chart",
        "Pressure Trends",
        "Precipitation Chances",
        "Haptic Feedback Alerts",
        "Live Activity",
        "Interactive Radar Layers",
        "Shareable Weather Cards",
        "CarPlay Forecast Screen"
    ]),
    Project(name: "WeatherWizard", features: [
        "Hourly Forecast",
        "10-Day Outlook",
        "Radar Map",
        "Severe Storm Alerts",
        "Air Quality Index",
        "UV Index",
        "Sunrise & Sunset",
        "Widget Support",
        "Location-Based Notifications",
        "WatchOS Companion",
        "iPad Split View",
        "Dark Mode",
        "Siri Shortcuts",
        "Home Screen Quick Actions",
        "Offline Caching",
        "Customizable Themes",
        "Wind Speed Graph",
        "Humidity Chart",
        "Pressure Trends",
        "Precipitation Chances",
        "Haptic Feedback Alerts",
        "Live Activity",
        "Interactive Radar Layers",
        "Shareable Weather Cards",
        "CarPlay Forecast Screen",
        "Hourly Forecast",
        "10-Day Outlook",
        "Radar Map",
        "Severe Storm Alerts",
        "Air Quality Index",
        "UV Index",
        "Sunrise & Sunset",
        "Widget Support",
        "Location-Based Notifications",
        "WatchOS Companion",
        "iPad Split View",
        "Dark Mode",
        "Siri Shortcuts",
        "Home Screen Quick Actions",
        "Offline Caching",
        "Customizable Themes",
        "Wind Speed Graph",
        "Humidity Chart",
        "Pressure Trends",
        "Precipitation Chances",
        "Haptic Feedback Alerts",
        "Live Activity",
        "Interactive Radar Layers",
        "Shareable Weather Cards",
        "CarPlay Forecast Screen"
    ]),
    Project(name: "BudgetBuddy", features: [
        "Expense Tracking",
        "Recurring Bills Reminders",
        "Multi-Currency Support",
        "Budget Goals",
        "Spending Categories",
        "Savings Tracker",
        "Export to CSV",
        "Bill Payment Notifications",
        "Dark Mode",
        "Widgets for Quick View",
        "Hourly Forecast",
        "10-Day Outlook",
        "Radar Map",
        "Severe Storm Alerts",
        "Air Quality Index",
        "UV Index",
        "Sunrise & Sunset",
        "Widget Support",
        "Location-Based Notifications",
        "WatchOS Companion",
        "iPad Split View",
        "Dark Mode",
        "Siri Shortcuts",
        "Home Screen Quick Actions",
        "Offline Caching",
        "Customizable Themes",
        "Wind Speed Graph",
        "Humidity Chart",
        "Pressure Trends",
        "Precipitation Chances",
        "Haptic Feedback Alerts",
        "Live Activity",
        "Interactive Radar Layers",
        "Shareable Weather Cards",
        "CarPlay Forecast Screen"
    ]),
    Project(name: "FitTrack", features: [
        "Workout Plans",
        "Calorie Counter",
        "Step Tracker",
        "Heart Rate Monitor",
        "Sleep Analysis",
        "Water Intake Reminders",
        "GPS Run Tracking",
        "Apple Watch Support",
        "Goal Setting",
        "Progress Charts",
        "Hourly Forecast",
        "10-Day Outlook",
        "Radar Map",
        "Severe Storm Alerts",
        "Air Quality Index",
        "UV Index",
        "Sunrise & Sunset",
        "Widget Support",
        "Location-Based Notifications",
        "WatchOS Companion",
        "iPad Split View",
        "Dark Mode",
        "Siri Shortcuts",
        "Home Screen Quick Actions",
        "Offline Caching",
        "Customizable Themes",
        "Wind Speed Graph",
        "Humidity Chart",
        "Pressure Trends",
        "Precipitation Chances",
        "Haptic Feedback Alerts",
        "Live Activity",
        "Interactive Radar Layers",
        "Shareable Weather Cards",
        "CarPlay Forecast Screen"
    ]),
    Project(name: "RecipeMaster", features: [
        "Recipe Search",
        "Meal Planner",
        "Shopping List",
        "Nutritional Info",
        "Favorites",
        "Voice Search",
        "Offline Recipes",
        "Cooking Mode",
        "Share Recipes",
        "Ingredient Substitutions",
        "Hourly Forecast",
        "10-Day Outlook",
        "Radar Map",
        "Severe Storm Alerts",
        "Air Quality Index",
        "UV Index",
        "Sunrise & Sunset",
        "Widget Support",
        "Location-Based Notifications",
        "WatchOS Companion",
        "iPad Split View",
        "Dark Mode",
        "Siri Shortcuts",
        "Home Screen Quick Actions",
        "Offline Caching",
        "Customizable Themes",
        "Wind Speed Graph",
        "Humidity Chart",
        "Pressure Trends",
        "Precipitation Chances",
        "Haptic Feedback Alerts",
        "Live Activity",
        "Interactive Radar Layers",
        "Shareable Weather Cards",
        "CarPlay Forecast Screen"
    ]),
    Project(name: "TravelMate", features: [
        "Flight Tracker",
        "Hotel Booking",
        "Currency Converter",
        "Weather Forecast",
        "Trip Planner",
        "Offline Maps",
        "Travel Itinerary",
        "Local Attractions",
        "Language Translator",
        "Expense Tracker",
        "Hourly Forecast",
        "10-Day Outlook",
        "Radar Map",
        "Severe Storm Alerts",
        "Air Quality Index",
        "UV Index",
        "Sunrise & Sunset",
        "Widget Support",
        "Location-Based Notifications",
        "WatchOS Companion",
        "iPad Split View",
        "Dark Mode",
        "Siri Shortcuts",
        "Home Screen Quick Actions",
        "Offline Caching",
        "Customizable Themes",
        "Wind Speed Graph",
        "Humidity Chart",
        "Pressure Trends",
        "Precipitation Chances",
        "Haptic Feedback Alerts",
        "Live Activity",
        "Interactive Radar Layers",
        "Shareable Weather Cards",
        "CarPlay Forecast Screen"
    ]),
    Project(name: "Learnify", features: [
        "Course Library",
        "Video Lessons",
        "Quizzes",
        "Offline Access",
        "Progress Tracker",
        "Certificates",
        "Dark Mode",
        "Bookmarks",
        "Push Notifications",
        "Multi-Language Support",
        "Hourly Forecast",
        "10-Day Outlook",
        "Radar Map",
        "Severe Storm Alerts",
        "Air Quality Index",
        "UV Index",
        "Sunrise & Sunset",
        "Widget Support",
        "Location-Based Notifications",
        "WatchOS Companion",
        "iPad Split View",
        "Dark Mode",
        "Siri Shortcuts",
        "Home Screen Quick Actions",
        "Offline Caching",
        "Customizable Themes",
        "Wind Speed Graph",
        "Humidity Chart",
        "Pressure Trends",
        "Precipitation Chances",
        "Haptic Feedback Alerts",
        "Live Activity",
        "Interactive Radar Layers",
        "Shareable Weather Cards",
        "CarPlay Forecast Screen"
    ]),
    Project(name: "ShopSmart", features: [
        "Price Comparison",
        "Barcode Scanner",
        "Wishlist",
        "Discount Alerts",
        "Order Tracking",
        "Reviews & Ratings",
        "Store Locator",
        "Secure Checkout",
        "Favorites",
        "Flash Sale Notifications",
        "Hourly Forecast",
        "10-Day Outlook",
        "Radar Map",
        "Severe Storm Alerts",
        "Air Quality Index",
        "UV Index",
        "Sunrise & Sunset",
        "Widget Support",
        "Location-Based Notifications",
        "WatchOS Companion",
        "iPad Split View",
        "Dark Mode",
        "Siri Shortcuts",
        "Home Screen Quick Actions",
        "Offline Caching",
        "Customizable Themes",
        "Wind Speed Graph",
        "Humidity Chart",
        "Pressure Trends",
        "Precipitation Chances",
        "Haptic Feedback Alerts",
        "Live Activity",
        "Interactive Radar Layers",
        "Shareable Weather Cards",
        "CarPlay Forecast Screen"
    ]),
    Project(name: "PetCare", features: [
        "Pet Profiles",
        "Vet Appointments",
        "Vaccination Reminders",
        "Pet Food Tracker",
        "Activity Log",
        "Weight Monitoring",
        "Photo Gallery",
        "Lost Pet Alerts",
        "Nearby Pet Services",
        "Medication Schedule",
        "Hourly Forecast",
        "10-Day Outlook",
        "Radar Map",
        "Severe Storm Alerts",
        "Air Quality Index",
        "UV Index",
        "Sunrise & Sunset",
        "Widget Support",
        "Location-Based Notifications",
        "WatchOS Companion",
        "iPad Split View",
        "Dark Mode",
        "Siri Shortcuts",
        "Home Screen Quick Actions",
        "Offline Caching",
        "Customizable Themes",
        "Wind Speed Graph",
        "Humidity Chart",
        "Pressure Trends",
        "Precipitation Chances",
        "Haptic Feedback Alerts",
        "Live Activity",
        "Interactive Radar Layers",
        "Shareable Weather Cards",
        "CarPlay Forecast Screen"
    ]),
    Project(name: "MovieMania", features: [
        "Now Playing",
        "Upcoming Movies",
        "Top Rated",
        "Search",
        "Watchlist",
        "Trailers",
        "Reviews",
        "Cast & Crew Info",
        "Showtimes",
        "Streaming Availability",
        "Hourly Forecast",
        "10-Day Outlook",
        "Radar Map",
        "Severe Storm Alerts",
        "Air Quality Index",
        "UV Index",
        "Sunrise & Sunset",
        "Widget Support",
        "Location-Based Notifications",
        "WatchOS Companion",
        "iPad Split View",
        "Dark Mode",
        "Siri Shortcuts",
        "Home Screen Quick Actions",
        "Offline Caching",
        "Customizable Themes",
        "Wind Speed Graph",
        "Humidity Chart",
        "Pressure Trends",
        "Precipitation Chances",
        "Haptic Feedback Alerts",
        "Live Activity",
        "Interactive Radar Layers",
        "Shareable Weather Cards",
        "CarPlay Forecast Screen",
        "Hourly Forecast",
        "10-Day Outlook",
        "Radar Map",
        "Severe Storm Alerts",
        "Air Quality Index",
        "UV Index",
        "Sunrise & Sunset",
        "Widget Support",
        "Location-Based Notifications",
        "WatchOS Companion",
        "iPad Split View",
        "Dark Mode",
        "Siri Shortcuts",
        "Home Screen Quick Actions",
        "Offline Caching",
        "Customizable Themes",
        "Wind Speed Graph",
        "Humidity Chart",
        "Pressure Trends",
        "Precipitation Chances",
        "Haptic Feedback Alerts",
        "Live Activity",
        "Interactive Radar Layers",
        "Shareable Weather Cards",
        "CarPlay Forecast Screen"
    ]),
    Project(name: "HomeControl", features: [
        "Smart Light Control",
        "Thermostat Adjustment",
        "Security Camera Feed",
        "Door Lock Control",
        "Energy Usage Monitor",
        "Scene Automation",
        "Voice Assistant Integration",
        "Appliance Scheduling",
        "Custom Scenes",
        "Alerts & Notifications",
        "Hourly Forecast",
        "10-Day Outlook",
        "Radar Map",
        "Severe Storm Alerts",
        "Air Quality Index",
        "UV Index",
        "Sunrise & Sunset",
        "Widget Support",
        "Location-Based Notifications",
        "WatchOS Companion",
        "iPad Split View",
        "Dark Mode",
        "Siri Shortcuts",
        "Home Screen Quick Actions",
        "Offline Caching",
        "Customizable Themes",
        "Wind Speed Graph",
        "Humidity Chart",
        "Pressure Trends",
        "Precipitation Chances",
        "Haptic Feedback Alerts",
        "Live Activity",
        "Interactive Radar Layers",
        "Shareable Weather Cards",
        "CarPlay Forecast Screen"
    ])
]

